swagger: '2.0'
info:
  version: 2.0.0
  title: eGov Property Tax Information System.
  description: >
    APIs for Property Tax module. This modules handles assessment of new
    properties, changes to existing properties (Detail Updates, division of
    property, etc.), 
    search of required properties and property tax calculation, demand generation, notices
    to enable ULBs to cmpletely manage the proeprties within their jurisdiction.
  contact:
    name: Ghanshyam Rawat
    email: ghanshyam.rawat@egovernments.org
schemes:
  - https
basePath: /properties/v2
x-common-path: >-
  https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml
paths:
  /_search:
    post:
      summary: Get the list of properties defined in the system.
      description: |
        Get the properties list based on the input parameters.
      parameters:
        - $ref: >-
            https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo
        - $ref: >-
            https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId
        - name: active
          in: query
          description: >-
            True will be set in cases where only active properties are needed
            and False will be set when inactive properties are needed and no
            value will be set when all properties are needed.
          required: false
          type: boolean
          format: varchar
          allowEmptyValue: true
        - name: propertyId
          in: query
          description: Primary key of Property object.
          required: false
          type: string
          format: varchar
        - name: assessmentNumber
          in: query
          required: false
          description: The unique reference number for a property.
          type: string
          minLength: 4
          maxLength: 128
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: oldAssessmentNumber
          in: query
          required: false
          description: The unique old assessment no for a Property.
          type: string
          minLength: 4
          maxLength: 128
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: locality
          in: query
          description: Locality boundary where the property is located.
          required: false
          type: integer
          format: int64
        - name: acknowldgementNumber
          in: query
          required: false
          description: The acknowldgement number no for a property.
          type: string
          minLength: 1
          maxLength: 64
          exclusiveMinimum: true
          exclusiveMaximum: false
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/PropertyResponse'
        '400':
          description: Invalid input.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Property
        
#########################################        
  /_create:
    post:
      summary: Create new properties.
      description: API to create new properties.
      parameters:
        - name: property
          in: body
          description: Details for the new property + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/PropertyRequest'
      responses:
        '201':
          description: Property(s) created sucessfully
          schema:
            $ref: '#/definitions/PropertyResponse'
        '400':
          description: Property(s) creation failed
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
      tags:
        - Property
#########################################        

  /_update:
    post:
      summary: Update existing properties.
      description: Updates a given `Property` with newer details.
      parameters:
        - name: property
          in: body
          description: Request header for the property Request.
          required: true
          schema:
            $ref: '#/definitions/PropertyRequest'
      tags:
        - Property
      responses:
        '200':
          description: Update Property(s) successful
          schema:
            $ref: '#/definitions/PropertyResponse'
        '400':
          description: Update Property(s) failed
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
definitions:
  PropertyInfo:
    type: object
    description: This is lightweight property object that can be used as reference by definitions needing property linking. Actual Property Object extends this to include more elaborate attributes of the property.
    properties:
      id:
        type: string
        description: Unique Identifier of the Property (UUID).
        readOnly: true
        minLength: 1
        maxLength: 64
      tenantId:
        type: string
        description: tenant id of the Property
        maxLength: 256
        minLength: 2
      acknowldgementNumber:
        type: string
        description: >-
          Acknowldgement number given to citizen on submitting the application
          for creation or modification of the property.
        maxLength: 64
        minLength: 1
        readOnly: true
      assessmentNumber:
        type: string
        description: >-
          UPIC (Unique Property Identification Number) of the Property. This is a
          unique in system. This is mandatory but always be generated on the
          final approval.
        maxLength: 256
        minLength: 2
        readOnly: true
      status:
        type: string
        description: status of the Property
        maxLength: 64
        minLength: 2
        enum:
          - ACTIVE
          - INACTIVE
      financialYear:
        type: string
        description: >-
              Latest tax paid year.
      propertyType:
        type: string
        description: >-
          Type of a property like Private, Vacant Land, State Government,
          Central Government etc.
        maxLength: 64
        minLength: 1
      owners:
        description: 'Property owners, these will be citizen users in system.'
        type: array
        items:
          $ref: '#/definitions/OwnerInfo'
      address:
            $ref: >-
              #/definitions/Address

#########################################        
          
  Property:
    allOf:
      - $ref: '#/definitions/PropertyInfo'
      - type: object
        description: A Object holds the basic data for a property
        properties:
          oldAssessmentNumber:
            type: string
            description: >-
              Old upic no of the Property. ULBs have the existing property in their
              system/manual records with their identification number, they want to
              continue the old reference number in this case the same identification
              number will be captured here.
            maxLength: 256
            minLength: 1
          assessmentDate:
            type: string
            format: date
            description: >-
              There will be work flow to create a new property in a system. The
              assessment date is the final approval and UPIC no generation date.
          creationReason:
            type: string
            description: >-
              New property comes into system either property is newly
              constructed or existing property got sub divided. Here the reason
              for creation will be captured.
            maxLength: 256
            minLength: 1
            enum:
              - NEWPROPERTY
              - SUBDIVISION
          occupancyDate:
            type: integer
            format: int64
            description: >-
              Property is constructed but the tax will be applicable only from
              the occupation date (time in epoch). System capture that date
              here.
          propertyDetail:
            $ref: '#/definitions/PropertyDetail'
        required:
          - address
          - boundary
          - propertyDetail
          - occupancyDate
  
#########################################              
          
  PropertyDetail:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the PropertyDetail
      source:
        type: string
        description: >-
          Source of a assessment data. The properties will be created in a
          system based on the data avaialble in their manual records or during
          field survey. There can be more from client to client.
        maxLength: 64
        minLength: 1
        enum:
          - MUNICIPAL_RECORDS
          - FIELD_SURVEY
      usage:
        type: string
        description: usage of the property
        maxLength: 64
        minLength: 1
        
      noOfFloors:
        type: integer
        format: int64
        description: no of floors in the property
      
      landArea:
        type: number
        format: float
        description: Land area of the property in sq ft
        
      buildUpArea:
        type: number
        format: float
        description: Total built up area in sq ft

      units:
        description: List of Units in the property. E.g. A property might have 2 units in ground floor and 1 ion first floor. Unit can be Room, floor or any bounded area with a defined usage.
        type: array
        items:
          $ref: '#/definitions/Unit'
      
      documents:
        description: >-
          The documents attached during assessment, modification or any
          transaction happened on the property.
        type: array
        items:
          $ref: '#/definitions/Document'
      
      additionalDetails:
        type: string
        description: 'The json (array of ''#/definitions/Factor'')'
      
      channel:
            type: string
            description: >-
              Property can be created from different channels Eg. System
              (properties created by ULB officials), CFC Counter (From citizen
              faciliation counters) etc. Here we are defining some known
              channels, there can be more client to client.
            maxLength: 64
            minLength: 4
            enum:
              - SYSTEM
              - CFC_COUNTER
              - CITIZEN
              - DATA_ENTRY
              - MIGRATION
        
#########################################        
        
  OwnerInfo:
    allOf:
      - $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-user/contracts/v1-0-0.yml#/definitions/User
      - type: object
        properties:
          isPrimaryOwner:
            type: boolean
            description: The owner is primary or not
          isCurrentOwner:
            type: boolean
            description: The owner is current owner or not
          ownerShipPercentage:
            type: number
            format: double
            description: Ownership percentage.
          ownerType:
            type: string
            description: 'Type of owner, based on this option rebate will be calculated.'
            maxLength: 32
            minLength: 4
            
#########################################        
            
  Address:
    allOf:
      - $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-0.yml#/definitions/Address
      - type: object
        description: Address of the property.
        properties:
          buildingName:
            type: string
            description: 'Name of the building'
            maxLength: 64
            minLength: 2
          street:
            type: string
            description: 'Street Name'
            maxLength: 64
            minLength: 2
          locality:
            $ref: https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egov-location/contracts/v11-0-0.yml#/definitions/Boundary
    
#########################################        '

  Document:
    type: object
    description: >-
      This object holds list of documents attached during the transaciton for a
      property
    properties:
      id:
        type: integer
        format: int64
        description: unique id of the Document.
      documentType:
        type: string
        description: >-
          unique document type code, should be validated with document type
          master
      fileStore:
        type: string
        description: File store reference key.

######################################### 

  Unit:
    type: object
    properties:
      id:
        type: string
        description: Unique Identifier of the Property(UUID).
      tenantId:
        type: string
        description: tenant id of the Property
        maxLength: 256
        minLength: 2
      floorNo:
        type: string
        description: floor no for the floor
        maxLength: 64
        minLength: 1
      unitType:
        type: string
        description: >-
          Unit type .
        maxLength: 64
        minLength: 1
      unitArea:
        type: number
        format: float
        description: Area of the defined Unit
      usage:
        type: array
        items:
         $ref: '#/definitions/UnitUsage'
#########################################

  UnitUsage:
    type: object
    description: Details of unit usage for a priod. 
    properties:
      usage:
        type: string
        description: usage of the property
        maxLength: 64
        minLength: 1
      fromDate:
        type: string
        description: start date for the unit usage.
        maxLength: 64
        minLength: 1
      toDate:
        type: string
        description: end date for the unit usage.
        maxLength: 64
        minLength: 1
      occupancyType:
        type: string
        description: end date for the unit usage.
        enum:
              - Owner
              - Tenant
        
#########################################

  PropertyRequest:
    description: >-
      Contract class to receive request. Array of Property items  are used in
      case of create . Where as single Property item is used for update
    properties:
      requestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
      properties:
        description: Used for search result and create only
        type: array
        minimum: 1
        maximum: 100
        items:
          $ref: '#/definitions/Property'
  PropertyResponse:
    description: >-
      Contract class to send response. Array of Property items  are used in case
      of search results or response for create. Where as single Property item is
      used for update
    properties:
      responseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      properties:
        description: Used for search result and create only
        type: array
        items:
          $ref: '#/definitions/Property'
          
#########################################        
  

